# Generated by Django 2.2.3 on 2019-10-06 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreArea', models.CharField(max_length=45)),
                ('descripcionArea', models.TextField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=45)),
                ('fechaRealizacion', models.DateTimeField(auto_now_add=True)),
                ('area', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectoApp.Area')),
            ],
            options={
                'verbose_name': 'Cuestionario',
                'verbose_name_plural': 'Cuestionarios',
            },
        ),
        migrations.CreateModel(
            name='CuestionarioRespondido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_supervisor', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=45)),
                ('fechaRealizacion', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoApp.Area')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('fecha_date', models.DateTimeField()),
                ('fecha_ingreso', models.DateTimeField()),
                ('sexo', models.CharField(choices=[('1', 'M'), ('2', 'F')], max_length=2)),
                ('no_empleado', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Posicion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta_Filtro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preguntaFiltro', models.CharField(max_length=200)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Pregunta Filtro',
            },
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePuesto', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name': 'Puesto',
                'verbose_name_plural': 'Puestos',
            },
        ),
        migrations.CreateModel(
            name='Seglog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SegLogKey', models.IntegerField()),
                ('SegLogFecha', models.DateTimeField()),
                ('SegLogHora', models.TimeField()),
                ('SegLogDetall', models.CharField(max_length=400)),
                ('SegLogComando', models.CharField(max_length=400)),
                ('SegLogIp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo Pregunta',
                'verbose_name_plural': 'Tipo Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Turnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(max_length=25)),
                ('hora_inicio', models.TimeField()),
                ('hora_final', models.TimeField()),
                ('activo', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaRespondida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=50)),
                ('respuesta', models.CharField(max_length=20)),
                ('CuestionarioRespondido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoApp.CuestionarioRespondido')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100)),
                ('cuestionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectoApp.Cuestionario')),
                ('tipoPregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipoPregunta', to='proyectoApp.TipoPregunta')),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=45)),
                ('email', models.CharField(max_length=70)),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoApp.Puesto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
            },
        ),
    ]
