# Generated by Django 2.2.3 on 2019-10-06 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipoPregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectoApp.TipoPregunta'),
        ),
    ]
