# Generated by Django 2.2.3 on 2019-10-06 05:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectoApp', '0002_auto_20191005_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='tipoPregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='proyectoApp.TipoPregunta'),
        ),
    ]
